/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminal;
import java.sql.*;
//import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class UserComplainRegStatus extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserComplainRegStatus
     */
    public UserComplainRegStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfirno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtchargeofcomplain = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtinspectorname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtupdatediscription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        txtdate = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("User Complain RegStatus");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Complain Registration");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 10, 250, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("FIR No");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 90, 70, 30);

        txtfirno.setText(" ");
        txtfirno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirnoActionPerformed(evt);
            }
        });
        jPanel1.add(txtfirno);
        txtfirno.setBounds(310, 70, 130, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText(" Complainer   Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(610, 70, 170, 30);

        txtchargeofcomplain.setText(" ");
        jPanel1.add(txtchargeofcomplain);
        txtchargeofcomplain.setBounds(310, 120, 270, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Charge of Complainer");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 120, 180, 30);

        jTextField2.setText(" ");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(790, 70, 270, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText(" Complainer  Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 180, 180, 30);

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(310, 160, 270, 70);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Region of  Complain");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(600, 120, 170, 30);

        jTextField4.setText(" ");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(790, 120, 270, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Suspector Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 250, 170, 30);

        txtinspectorname.setText(" ");
        jPanel1.add(txtinspectorname);
        txtinspectorname.setBounds(310, 250, 270, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Suspect's Address");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(610, 180, 170, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Types of Crime");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(600, 250, 170, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Date");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(120, 300, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 440, 170, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(700, 430, 160, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Update Date");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(600, 300, 170, 30);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(790, 290, 270, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Update Description");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(100, 370, 170, 30);

        txtupdatediscription.setColumns(20);
        txtupdatediscription.setRows(5);
        jScrollPane2.setViewportView(txtupdatediscription);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(310, 340, 270, 80);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(790, 160, 270, 70);
        jPanel1.add(txtdate);
        txtdate.setBounds(310, 300, 270, 30);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(790, 250, 270, 30);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(730, 500, 260, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(460, 70, 140, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(470, 430, 170, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String firno = txtfirno.getText();
        String chargeofcomplain=txtchargeofcomplain.getText();
        String address = txtaddress.getText();
        String inspector = txtinspectorname.getText();
        String date = txtdate.getText();
        String discription = txtupdatediscription.getText();
    
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/crimnal","root","");
           String sql="update usercomplain set chargeofcomplain='"+chargeofcomplain+"',complaineraddress='"+address+"',  suspectername='"+inspector+"',cdate='"+date+"', updesc='"+discription+"' where  firno='"+firno+"'";
        //String sql="update usercomplain set chargeofcomplainer='"+jTextField2.getText()+"',complainername='"+txtchargeofcomplain.getText()+"',  regionofcomplain='"+jTextField4.getText()+"',complaineraddress='"+txtaddress.getText()+"', suspectaddress='"+jTextArea3.getText()+"', suspectname='"+txtinspectorname.getText()+"', typeofcrime='"+jTextField7.getText()+"', cdate='"+txtdate.getText()+"', udate='"+jTextField8.getText()+"',updesc='"+txtupdatediscription.getText()+"', where  firno='"+txtfirno.getText()+"'";
          Statement st=con.createStatement();
            int res=st.executeUpdate(sql);

         if(res==1)
         {
              JOptionPane.showMessageDialog(this,"Sucessfully data Update");
              
        
         }
         else
         {
              JOptionPane.showMessageDialog(this,"Not update");

            }
            con.close();
        } catch (Exception e) {

            //JOptionPane.showMessageDialog(null,e.toString());
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        jTextField1.setText("");
//        jTextField2.setText("");
//        jTextField3.setText("");
//        jTextField4.setText("");
//        jTextField5.setText("");
//        jTextField7.setText("");
//        jTextField8.setText("");
//
//        //jTextField10.setText("");
//        jTextField6.setText("");
//        jTextArea1.setText("");
//        jTextArea2.setText("");
//        jTextArea3.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/crimnal", "root", "");

            String sql = "select*from usercomplain where firno='" + txtfirno.getText() + "'";
            java.sql.Statement ts = con.createStatement();
            ResultSet rs = ts.executeQuery(sql);
            if (rs.next()) {
                txtchargeofcomplain.setText(rs.getString(2));
                jTextField2.setText(rs.getString(3));
                jTextField4.setText(rs.getString(4));
                txtaddress.setText(rs.getString(5));
                jTextArea3.setText(rs.getString(6));
                txtinspectorname.setText(rs.getString(7));
                jTextField7.setText(rs.getString(8));
                txtdate.setText(rs.getString(9));
                //jDateChooser1.setDate;
                //jTextField8.setText(rs.getString(10));
            } else {
                JOptionPane.showMessageDialog(null, "Data not Found");
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtfirnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtchargeofcomplain;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtfirno;
    private javax.swing.JTextField txtinspectorname;
    private javax.swing.JTextArea txtupdatediscription;
    // End of variables declaration//GEN-END:variables
}
