/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminal;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class UserMostWanredPersonStatus extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserMostWanredPersonStatus
     */
    public UserMostWanredPersonStatus() {
        initComponents();
        fillcombBox();
    }
    private void fillcombBox()
    {
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/crimnal","root","");
            Statement st=con.createStatement();
            String sql="select typeofcrime from MostWanted";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                jComboBox1.addItem(rs.getString(1));
                
            }
            
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("User Most Wanted Person Status");

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Most Wanted Person");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 10, 370, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Types of Crime");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 50, 140, 17);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(380, 50, 200, 23);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Necr Name", "Address", "Age", "Gender", "date"
            }
        ));
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(10);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 90, 850, 490);

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(600, 50, 170, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/5.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    /*   try { Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","4321");
            Statement st=con.createStatement();
            String sql="select * from MostWanted";
            ResultSet rs=st.executeQuery(sql);
            int row=0;
            while(rs.next())
            
            {
               jTable1.getModel().setValueAt(rs.getString(1), row, 0);
                jTable1.getModel().setValueAt(rs.getString(2), row,1);
               jTable1.getModel().setValueAt(rs.getString(3), row,2);
               jTable1.getModel().setValueAt(rs.getString(4), row,3);
               jTable1.getModel().setValueAt(rs.getString(5), row,4);
               jTable1.getModel().setValueAt(rs.getString(6), row,5);
               jTable1.getModel().setValueAt(rs.getString(7), row,6);
               //jTable1.getModel().setValueAt(rs.getString(8), row,7);
               row++;
            }
            con.close();
        } catch (Exception e) {
        }
        */
int row=0;
        try { Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/crimnal","root","");
            Statement st=con.createStatement();
            String sql="select * from MostWanted where typeofcrime='"+jComboBox1.getSelectedItem()+"'";
            ResultSet rs=st.executeQuery(sql);
            if(rs.next())
            {
             jTable1.getModel().setValueAt(rs.getString(1), row, 0);
                jTable1.getModel().setValueAt(rs.getString(2), row,1);
               jTable1.getModel().setValueAt(rs.getString(3), row,2);
               jTable1.getModel().setValueAt(rs.getString(4), row,3);
              jTable1.getModel().setValueAt(rs.getString(5), row,4);
               jTable1.getModel().setValueAt(rs.getString(6), row,5);
              // jTable1.getModel().setValueAt(rs.getString(7), row,6);
               //jTable1.getModel().setValueAt(rs.getString(8), row,7);
               row++;
            }
              else
            {
            JOptionPane.showMessageDialog(null,"Data not Found");
            }
            con.close();
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
